on: [push, pull_request, workflow_dispatch]

jobs:
  build:
  runs-on: ubuntu-latest
      
   steps:
    - uses: actions/checkout@v4
    - uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
